### ISSUE TITLE
Gesture lock crash when changed master password

### ISSUE THREAD

**Issue by SpongeBobSun** [PuffOpenSource/Puff-Android#3]
Can reproduce every time.

**Comment by SpongeBobSun** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String sun.bob.leela.db.Account.getHash()' on a null object reference
    at sun.bob.leela.runnable.QuickPassRunnable.getPasswordHash(QuickPassRunnable.java:47)
    at sun.bob.leela.runnable.QuickPassRunnable.<init>(QuickPassRunnable.java:35)
    at sun.bob.leela.ui.activities.SetQuickPasswordActivity.checkQuickPass(SetQuickPasswordActivity.java:119)
    at sun.bob.leela.ui.activities.SetQuickPasswordActivity.access$300(SetQuickPasswordActivity.java:27)
    at sun.bob.leela.ui.activities.SetQuickPasswordActivity$1.onPatternDetected(SetQuickPasswordActivity.java:71)
    at com.eftimoff.patternview.PatternView.notifyPatternDetected(PatternView.java:409)
    at com.eftimoff.patternview.PatternView.handleActionUp(PatternView.java:807)
    at com.eftimoff.patternview.PatternView.onTouchEvent(PatternView.java:637)
    at android.view.View.dispatchTouchEvent(View.java:8547)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
    at android.view.View.dispatchPointerEvent(View.java:8742)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3693)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3750)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5823)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5797)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5768)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5913)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:143)
    at android.os.Looper.loop(Looper.java:195)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
